version: '2.1'
services:
  nginx:
    build: docker/nginx
    ports:
      - 2019:80
    volumes:
      - ./docker/nginx/logs/:/var/log/nginx
      - /home/samir2/www/lillydo/core:/var/www/core
  php:
    build: docker/php
    restart: always
    volumes:
      - /home/samir2/www/lillydo/core:/var/www/core
  composer:
    image: composer:1.7.2
    volumes:
      - "/home/samir2/www/lillydo/core:/app"
    command: install
